apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-210235-g9on-service
spec:
  selector:
    app: enterprise-system-210235-g9on
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
